### ISSUE TITLE
일간/주간/월간 랭킹 기능 제안

### ISSUE THREAD

**Issue by donghoony** [riroan/SchoolJoon#1]
특정 기간동안(일, 주, 월 등) 학교순위 상승 기여에 대한 랭킹 시스템이 있으면 좋을 것 같아요!

**Comment by riroan** [comment]
한 1주단위로 푼문제수 랭킹만들면 재밌을거같네요.
좋은 의견 감사합니다 :D

**Comment by donghoony** [comment]
학교순위 상승 기여가 아닌 푼 문제수 랭크로 돼 있는데, 의도된 것인가요 ?

**Comment by riroan** [comment]
우리학교 학생이 안 푼 문제를 푼 문제에 대한 랭크였군요. 스위칭 가능하게 수정하겠습니다.

**Comment by riroan** [comment]
반영했습니다.

**Comment by donghoony** [comment]
팬이에요 :fan:
