### ISSUE TITLE
FastAPI based pagination

### ISSUE THREAD

**Issue by donghoony** [riroan/SchoolJoon#6]
API에서 모든 정보를 받은 뒤 페이징하는 것 같습니다.
알고리즘 별 정리에서 꽤 로드 시간이 걸립니다. 백엔드 쪽에서 페이징해서 넘겨주면 빠르게 해결될 것 같아요!

**Comment by riroan** [comment]
서버pc를 aws의 프리티어로 사용하고 있어서 버튼 누를때마다 api를 호출하는식으로 하면 무리가 갈거같아서 이렇게 구현하긴 했습니다. 실험해보고 문제가 없다면 바꿔보도록 하겠습니다.

**Comment by riroan** [comment]
쿼리 처리하는데 있어서 굉장히 비효율적인 부분을 발견해서 수정했습니다.
속도가 2배~50배까지 빨라짐을 확인했습니다.

아직 개선의 요소가 보이는거 같아 최적화는 지속적으로 고민하여 개선하겠습니다.
